### ISSUE TITLE
Ability to specify default storage class

### ISSUE THREAD

**Issue by awels** [openshift/local-storage-operator#16]
I would to have the ability to set a field in the cr to have the created storage class be the default. I can patch it in after the sc is created of course, but being able to do it from the cr would be nice.

**Comment by j-griffith** [comment]
Setting the default storage is class is typically a post install operation for plugins, IMO it should stay that way.  Adding a flag to the operator might be handy, but it's just another "knob" that may or may not be useful, and it incurs additional checks for things like "is there already a default" etc.

It's my opinion that 
`patch sc local-storage -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'`

Is not difficult at all; and you should be explicit if you're doing things like changing default class; just my 2 cents.

**Comment by awels** [comment]
Fair enough, closing.

**Comment by zhengbin78** [comment]
Regarding this feature, I put forward my own opinion, because the storage class follows the local-storage-operator and is created automatically, but for unknown reasons, the is-default-class disappeared shortly after. I tried to find out why it disappeared.
This shows that adding is-default-class has some value in functionality. 
The version I use is: local-storage-operator.4.3.5-202003020549
